export const ASSET_UNIVERSE = [
  // Top US Equities (S&P 100 Sample)
  { ticker: "AAPL", name: "Apple Inc.", type: "EQUITY", region: "US" },
  { ticker: "MSFT", name: "Microsoft Corp.", type: "EQUITY", region: "US" },
  { ticker: "NVDA", name: "NVIDIA Corp.", type: "EQUITY", region: "US" },
  { ticker: "AMZN", name: "Amazon.com Inc.", type: "EQUITY", region: "US" },
  { ticker: "META", name: "Meta Platforms", type: "EQUITY", region: "US" },
  { ticker: "GOOGL", name: "Alphabet Inc.", type: "EQUITY", region: "US" },
  { ticker: "TSLA", name: "Tesla Inc.", type: "EQUITY", region: "US" },
  { ticker: "JPM", name: "JPMorgan Chase", type: "EQUITY", region: "US" },
  { ticker: "V", name: "Visa Inc.", type: "EQUITY", region: "US" },
  { ticker: "JNJ", name: "Johnson & Johnson", type: "EQUITY", region: "US" },
  { ticker: "WMT", name: "Walmart Inc.", type: "EQUITY", region: "US" },
  { ticker: "PG", name: "Procter & Gamble", type: "EQUITY", region: "US" },
  { ticker: "XOM", name: "Exxon Mobil", type: "EQUITY", region: "US" },
  { ticker: "UNH", name: "UnitedHealth Group", type: "EQUITY", region: "US" },
  { ticker: "MA", name: "Mastercard Inc.", type: "EQUITY", region: "US" },
  { ticker: "HD", name: "Home Depot", type: "EQUITY", region: "US" },
  { ticker: "CVX", name: "Chevron Corp.", type: "EQUITY", region: "US" },
  { ticker: "LLY", name: "Eli Lilly & Co.", type: "EQUITY", region: "US" },
  { ticker: "MRK", name: "Merck & Co.", type: "EQUITY", region: "US" },
  { ticker: "PEP", name: "PepsiCo", type: "EQUITY", region: "US" },
  { ticker: "KO", name: "Coca-Cola Co.", type: "EQUITY", region: "US" },

  // Top Indian Equities (NIFTY 50 Sample)
  { ticker: "RELIANCE.NS", name: "Reliance Industries", type: "EQUITY", region: "IND" },
  { ticker: "TCS.NS", name: "Tata Consultancy Services", type: "EQUITY", region: "IND" },
  { ticker: "HDFCBANK.NS", name: "HDFC Bank", type: "EQUITY", region: "IND" },
  { ticker: "ICICIBANK.NS", name: "ICICI Bank", type: "EQUITY", region: "IND" },
  { ticker: "INFY.NS", name: "Infosys", type: "EQUITY", region: "IND" },
  { ticker: "ITC.NS", name: "ITC Ltd.", type: "EQUITY", region: "IND" },
  { ticker: "SBIN.NS", name: "State Bank of India", type: "EQUITY", region: "IND" },
  { ticker: "BHARTIARTL.NS", name: "Bharti Airtel", type: "EQUITY", region: "IND" },
  { ticker: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", type: "EQUITY", region: "IND" },
  { ticker: "LT.NS", name: "Larsen & Toubro", type: "EQUITY", region: "IND" },
  { ticker: "AXISBANK.NS", name: "Axis Bank", type: "EQUITY", region: "IND" },
  { ticker: "HINDUNILVR.NS", name: "Hindustan Unilever", type: "EQUITY", region: "IND" },
  { ticker: "BAJFINANCE.NS", name: "Bajaj Finance", type: "EQUITY", region: "IND" },
  { ticker: "MARUTI.NS", name: "Maruti Suzuki", type: "EQUITY", region: "IND" },
  { ticker: "SUNPHARMA.NS", name: "Sun Pharma", type: "EQUITY", region: "IND" },

  // Major ETFs
  { ticker: "SPY", name: "SPDR S&P 500 ETF", type: "ETF", region: "US" },
  { ticker: "QQQ", name: "Invesco QQQ Trust", type: "ETF", region: "US" },
  { ticker: "DIA", name: "SPDR Dow Jones Industrial", type: "ETF", region: "US" },
  { ticker: "IWM", name: "iShares Russell 2000", type: "ETF", region: "US" },
  { ticker: "VOO", name: "Vanguard S&P 500", type: "ETF", region: "US" },
  { ticker: "HYG", name: "iShares iBoxx High Yield Corp", type: "ETF", region: "US" },
  { ticker: "LQD", name: "iShares iBoxx Inv Grade Corp", type: "ETF", region: "US" },
  { ticker: "TLT", name: "iShares 20+ Year Treasury", type: "ETF", region: "US" },
  { ticker: "NIFTYBEES.NS", name: "Nippon India Nifty 50 BeES", type: "ETF", region: "IND" },
  { ticker: "BANKBEES.NS", name: "Nippon India Bank BeES", type: "ETF", region: "IND" },
  { ticker: "LIQUIDBEES.NS", name: "Nippon India Liquid BeES", type: "ETF", region: "IND" },

  // Government Bonds / Rates
  { ticker: "^TNX", name: "US Treasury 10-Year Yield", type: "GOV_BOND", region: "US" },
  { ticker: "^TYX", name: "US Treasury 30-Year Yield", type: "GOV_BOND", region: "US" },
  { ticker: "^IRX", name: "US Treasury 13-Week Bill", type: "GOV_BOND", region: "US" },
  { ticker: "^FVX", name: "US Treasury 5-Year Yield", type: "GOV_BOND", region: "US" }
];
